### PR TITLE
verify chap12

### PR DESCRIPTION
**Pull request by suredream**

### CODE REVIEW

**Comment by suredream** [comment]
@qiangmzsx  hi, may I understand why my two MR have been merged but I am not in the contributors list? I don't mind, just curious.

**Comment by qiangmzsx** [comment]
> @qiangmzsx hi, may I understand why my two MR have been merged but I am not in the contributors list? I don't mind, just curious.

出现这样的情况，可能是因为你提交的git账号记录并没有使用github的，你查看一下。

**Comment by qiangmzsx** [comment]
> _ No description provided. _

https://docs.github.com/cn/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user

**Comment by suredream** [comment]
我查了 git log 是用了 github 的，只是 junxiong360@gmail.com 被写成了 jun.xiong360@gmail.com，这也会造成问题吗？

**Comment by qiangmzsx** [comment]
> 我查了 git log 是用了 github 的，只是 [junxiong360@gmail.com](mailto:junxiong360@gmail.com) 被写成了 [jun.xiong360@gmail.com](mailto:jun.xiong360@gmail.com)，这也会造成问题吗？

只要在github没有对应的帐号就不能

**Pull request merged**
